      INCLUDE 'LIBRARY\MML_U2SA.FOR'
      INCLUDE 'LIBRARY\CMAP_LIBRARY.FOR'
      IMPLICIT REAL*8(A-H, O-Z)
      DIMENSION T(3,3), SIG(3), DEV_SIG(4), DEV_SIG0(3), DSIG(3)
      COMMON /KSIZE/ NDIM1,NDIM2,NDIM3,NDIM4,NDIM5,NDIM6,NDIM7,NDIM8
      SIG=0.D0
      SIG(1)=1.D0
      NDIM2=1
      NDIM3=3
      NDIM6=4
      CALL DEVIATORIC(SIG,DEV_SIG)
      CALL DEVIATORIC_TRANS(DEV_SIG,DEV_SIG0)
      PRINT *, SIG
      PRINT *, DEV_SIG
      PRINT *, DEV_SIG0
      PRINT *, '-----------------------'
      CALL DEVIATORIC_TENS(T)
      DSIG=MATMUL(T,SIG)
      PRINT *, DSIG

      END